language: c
compiler:
  - gcc
#  - clang
sudo: false
addons:
  apt:
    packages:
    - tcl
    - bison
    - flex
    - gcc-multilib

env:
   - OV_ARCH_BITWIDTH=32 DB_COMMANDS=no_dbcommands
   - OV_ARCH_BITWIDTH=64 DB_COMMANDS=dbcommands
#fb_dbcommands does not compile with 32 bit on the 64 bit travis

script:
   - cd ./build
   - tclsh ./acplt_build.tcl $DB_COMMANDS $OV_ARCH_BITWIDTH

after_failure:
   - tail -n 40 acplt_build.log
   
